local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Herokuで利用する場合は、Amazon S3などのクラウドストレージの設定も必要です
# 例：
# amazon:
#   service: S3
#   access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#   secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#   region: <%= ENV['AWS_REGION'] %>
#   bucket: <%= ENV['AWS_BUCKET'] %>